In [3]:
#install pyzipcode
pip install pyzipcode

Collecting pyzipcode
  Downloading pyzipcode-3.0.1.tar.gz (1.9 MB)
Building wheels for collected packages: pyzipcode
  Building wheel for pyzipcode (setup.py): started
  Building wheel for pyzipcode (setup.py): finished with status 'done'
  Created wheel for pyzipcode: filename=pyzipcode-3.0.1-py3-none-any.whl size=1932419 sha256=2dde5f21ad621fbcbc6cd1839a9fbe3ea369bd49cba973d2a5a8ebf471e2279e
  Stored in directory: c:\users\conno\appdata\local\pip\cache\wheels\f6\01\8e\7424c7e867eb5db7bb9531b09b4d968f23e5ac45ec5e7c3cb3
Successfully built pyzipcode
Installing collected packages: pyzipcode
Successfully installed pyzipcode-3.0.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#import libraries
from pyzipcode import ZipCodeDatabase
import pandas as pd
import numpy as np

In [47]:
#assign zipcode database
zcdb = ZipCodeDatabase()

#export csv
#zcdb.to_csv('ZipCodeDatabase.csv')

In [48]:
type(zcdb)

pyzipcode.ZipCodeDatabase

In [ ]:
#couldn't get this to work
#import zipcodes for missing games
weather = pd.read_csv('C:/Users/conno/OneDrive/Desktop/STAT 8940 - Applied Analysis Project/Data/missing_weather_type3.csv')

#list of zipcode attributes
weather_zip = []
for i in range(len(weather)-1):
    weather_zip.append(zcdb[weather["zip"][i]])
weather_zip

In [39]:
zcdb[weather["zip"][1]]

ZipCode(zip='32202', city='Jacksonville', state='FL', longitude=-81.65101, latitude=30.328539, timezone=-5, dst=1)

In [14]:
weather["zip"][1]

'32202'

In [56]:
#I think the weather dataframe is mucking up the weather search below.
#del weather

NameError: name 'weather' is not defined

In [57]:
#used to retrieve and parse historical weather data from World Weather
#Online into pandas DataFrame and CSV file
#pip install wwo-hist
from wwo_hist import retrieve_hist_data
zipcode = ["32202"]
hist_weather_data_1 = retrieve_hist_data("d44e502519aa4821af5205304211704",
                                zipcode,
                                "13-SEP-2015",
                                "13-SEP-2015",
                                6,
                                location_label = False,
                                export_csv = True,
                                store_df = True)

Retrieving weather data for 32202


Currently retrieving data for 32202: from 2015-09-13 to 2015-09-13
Time elapsed (hh:mm:ss.ms) 0:00:00.583741


export 32202 completed!

In [68]:
#can this be inserted into an empty list?
temp = []
temp.append(hist_weather_data_1)
temp[0]

[            date_time maxtempC mintempC totalSnow_cm sunHour uvIndex  \
 0 2015-09-13 00:00:00       29       21          0.0    11.6       6
 1 2015-09-13 06:00:00       29       21          0.0    11.6       6
 2 2015-09-13 12:00:00       29       21          0.0    11.6       6
 3 2015-09-13 18:00:00       29       21          0.0    11.6       6

   moon_illumination  moonrise   moonset   sunrise  ... WindGustKmph  \
 0                 0  07:25 AM  07:51 PM  07:10 AM  ...           10
 1                 0  07:25 AM  07:51 PM  07:10 AM  ...           14
 2                 0  07:25 AM  07:51 PM  07:10 AM  ...            5
 3                 0  07:25 AM  07:51 PM  07:10 AM  ...           11

   cloudcover humidity precipMM pressure tempC visibility winddirDegree  \
 0        100       98      0.0     1011    23          0           251
 1         30       93      0.1     1013    21         10           338
 2          7       41      0.0     1014    29         10           319
 3          0       51      0.0     1015    24         10           350

   windspeedKmph location
 0             6    32202
 1             9    32202
 2             4    32202
 3             5    32202

 [4 rows x 25 columns]]

In [59]:
type(hist_weather_data_1)

list

In [88]:
weather = pd.read_csv('C:/Users/conno/OneDrive/Desktop/STAT 8940 - Applied Analysis Project/Data/missing_weather_type3.csv')
#check index range
#range(len(weather)-1)
#weather["game_date"][70]
#zipcode = [weather["zip"][1]]
#zipcode
print(weather.columns)
weather["game_date"][5:12]

Index(['game_date', 'weather', 'stadium_id', 'stadium', 'game_stadium',
       'start_time', 'address', 'zip', 'timezone', 'local_start_time'],
      dtype='object')

5     15-Nov-2015
6     15-Nov-2015
7     19-Nov-2015
8     29-Nov-2015
9     29-Nov-2015
10    13-Dec-2015
11    10-Dec-2015
Name: game_date, dtype: object

In [89]:
#create list to input weather data
#hist_weather_data = []

for i in range(len(weather)-1-5):
    zipcode = [weather["zip"][i+5]]#the function wants a list
    temp = retrieve_hist_data("d44e502519aa4821af5205304211704",
                                zipcode,
                                weather["game_date"][i+5],
                                weather["game_date"][i+5],
                                6,
                                location_label = False,
                                export_csv = True,
                                store_df = True)
    hist_weather_data.append(temp)

Retrieving weather data for 54307


Currently retrieving data for 54307: from 2015-11-15 to 2015-11-15
Time elapsed (hh:mm:ss.ms) 0:00:01.574194


export 54307 completed!




Retrieving weather data for 80204


Currently retrieving data for 80204: from 2015-11-15 to 2015-11-15
Time elapsed (hh:mm:ss.ms) 0:00:00.487009


export 80204 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2015-11-19 to 2015-11-19
Time elapsed (hh:mm:ss.ms) 0:00:00.513664


export 32202 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2015-11-29 to 2015-11-29
Time elapsed (hh:mm:ss.ms) 0:00:00.459415


export 07073 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2015-11-29 to 2015-11-29
Time elapsed (hh:mm:ss.ms) 0:00:00.503544


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2015-12-13 to 2015-12-13
Time elapsed (hh:mm:ss.ms) 0:00:00.478196


export 32202 completed!




Retrieving weather data for 85305


Currently retrieving data for 85305: from 2015-12-10 to 2015-12-10
Time elapsed (hh:mm:ss.ms) 0:00:00.437756


export 85305 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2015-12-13 to 2015-12-13
Time elapsed (hh:mm:ss.ms) 0:00:00.451025


export 07073 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2015-12-20 to 2015-12-20
Time elapsed (hh:mm:ss.ms) 0:00:01.527599


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-09-11 to 2016-09-11
Time elapsed (hh:mm:ss.ms) 0:00:00.421075


export 32202 completed!




Retrieving weather data for 44114


Currently retrieving data for 44114: from 2016-09-18 to 2016-09-18
Time elapsed (hh:mm:ss.ms) 0:00:01.442638


export 44114 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-09-25 to 2016-09-25
Time elapsed (hh:mm:ss.ms) 0:00:00.459414


export 32202 completed!




Retrieving weather data for 33056


Currently retrieving data for 33056: from 2016-09-25 to 2016-09-25
Time elapsed (hh:mm:ss.ms) 0:00:00.479813


export 33056 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-09-25 to 2016-09-25
Time elapsed (hh:mm:ss.ms) 0:00:00.524598


export 54307 completed!




Retrieving weather data for 64129


Currently retrieving data for 64129: from 2016-09-25 to 2016-09-25
Time elapsed (hh:mm:ss.ms) 0:00:00.516719


export 64129 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2016-10-02 to 2016-10-02
Time elapsed (hh:mm:ss.ms) 0:00:00.557972


export 07073 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-10-09 to 2016-10-09
Time elapsed (hh:mm:ss.ms) 0:00:00.635354


export 54307 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-10-16 to 2016-10-16
Time elapsed (hh:mm:ss.ms) 0:00:00.469913


export 54307 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2016-10-23 to 2016-10-23
Time elapsed (hh:mm:ss.ms) 0:00:00.493093


export 07073 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-10-20 to 2016-10-20
Time elapsed (hh:mm:ss.ms) 0:00:00.572684


export 54307 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-10-23 to 2016-10-23
Time elapsed (hh:mm:ss.ms) 0:00:00.431414


export 32202 completed!




Retrieving weather data for 44114


Currently retrieving data for 44114: from 2016-11-06 to 2016-11-06
Time elapsed (hh:mm:ss.ms) 0:00:00.439528


export 44114 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-11-06 to 2016-11-06
Time elapsed (hh:mm:ss.ms) 0:00:00.451320


export 54307 completed!




Retrieving weather data for 64129


Currently retrieving data for 64129: from 2016-11-06 to 2016-11-06
Time elapsed (hh:mm:ss.ms) 0:00:00.535556


export 64129 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-11-13 to 2016-11-13
Time elapsed (hh:mm:ss.ms) 0:00:00.421727


export 32202 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2016-11-13 to 2016-11-13
Time elapsed (hh:mm:ss.ms) 0:00:00.443540


export 07073 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-12-04 to 2016-12-04
Time elapsed (hh:mm:ss.ms) 0:00:00.471697


export 32202 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-12-04 to 2016-12-04
Time elapsed (hh:mm:ss.ms) 0:00:00.460081


export 54307 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-12-11 to 2016-12-11
Time elapsed (hh:mm:ss.ms) 0:00:00.419146


export 32202 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-12-11 to 2016-12-11
Time elapsed (hh:mm:ss.ms) 0:00:01.718355


export 54307 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2016-12-24 to 2016-12-24
Time elapsed (hh:mm:ss.ms) 0:00:00.633798


export 54307 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2016-12-24 to 2016-12-24
Time elapsed (hh:mm:ss.ms) 0:00:00.624649


export 32202 completed!




Retrieving weather data for 33056


Currently retrieving data for 33056: from 2017-01-01 to 2017-01-01
Time elapsed (hh:mm:ss.ms) 0:00:00.458563


export 33056 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2017-11-05 to 2017-11-05
Time elapsed (hh:mm:ss.ms) 0:00:00.423697


export 32202 completed!




Retrieving weather data for 33056


Currently retrieving data for 33056: from 2017-11-05 to 2017-11-05
Time elapsed (hh:mm:ss.ms) 0:00:00.532131


export 33056 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2017-11-12 to 2017-11-12
Time elapsed (hh:mm:ss.ms) 0:00:00.497157


export 32202 completed!




Retrieving weather data for 85305


Currently retrieving data for 85305: from 2017-11-09 to 2017-11-09
Time elapsed (hh:mm:ss.ms) 0:00:00.464869


export 85305 completed!




Retrieving weather data for 44114


Currently retrieving data for 44114: from 2017-11-19 to 2017-11-19
Time elapsed (hh:mm:ss.ms) 0:00:00.469153


export 44114 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2017-12-03 to 2017-12-03
Time elapsed (hh:mm:ss.ms) 0:00:00.479267


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2017-12-10 to 2017-12-10
Time elapsed (hh:mm:ss.ms) 0:00:00.476624


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2017-12-17 to 2017-12-17
Time elapsed (hh:mm:ss.ms) 0:00:00.491940


export 32202 completed!




Retrieving weather data for 07073


Currently retrieving data for 07073: from 2017-12-24 to 2017-12-24
Time elapsed (hh:mm:ss.ms) 0:00:01.143080


export 07073 completed!




Retrieving weather data for 44114


Currently retrieving data for 44114: from 2018-09-20 to 2018-09-20
Time elapsed (hh:mm:ss.ms) 0:00:00.612074


export 44114 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2018-09-23 to 2018-09-23
Time elapsed (hh:mm:ss.ms) 0:00:01.022011


export 32202 completed!




Retrieving weather data for 30313


Currently retrieving data for 30313: from 2018-10-14 to 2018-10-14
Time elapsed (hh:mm:ss.ms) 0:00:00.816823


export 30313 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2018-10-21 to 2018-10-21
Time elapsed (hh:mm:ss.ms) 0:00:00.615271


export 32202 completed!




Retrieving weather data for 90746


Currently retrieving data for 90746: from 2018-12-09 to 2018-12-09
Time elapsed (hh:mm:ss.ms) 0:00:00.562051


export 90746 completed!




Retrieving weather data for 64129


Currently retrieving data for 64129: from 2018-12-13 to 2018-12-13
Time elapsed (hh:mm:ss.ms) 0:00:00.653896


export 64129 completed!




Retrieving weather data for 30313


Currently retrieving data for 30313: from 2019-09-15 to 2019-09-15
Time elapsed (hh:mm:ss.ms) 0:00:00.804023


export 30313 completed!




Retrieving weather data for 64129


Currently retrieving data for 64129: from 2019-09-22 to 2019-09-22
Time elapsed (hh:mm:ss.ms) 0:00:00.940906


export 64129 completed!




Retrieving weather data for 30313


Currently retrieving data for 30313: from 2019-10-20 to 2019-10-20
Time elapsed (hh:mm:ss.ms) 0:00:00.458053


export 30313 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2019-10-27 to 2019-10-27
Time elapsed (hh:mm:ss.ms) 0:00:00.945742


export 32202 completed!




Retrieving weather data for 90746


Currently retrieving data for 90746: from 2019-11-03 to 2019-11-03
Time elapsed (hh:mm:ss.ms) 0:00:00.487177


export 90746 completed!




Retrieving weather data for 54307


Currently retrieving data for 54307: from 2019-11-10 to 2019-11-10
Time elapsed (hh:mm:ss.ms) 0:00:00.917944


export 54307 completed!




Retrieving weather data for 44114


Currently retrieving data for 44114: from 2019-11-14 to 2019-11-14
Time elapsed (hh:mm:ss.ms) 0:00:00.455154


export 44114 completed!




Retrieving weather data for 33056


Currently retrieving data for 33056: from 2019-12-01 to 2019-12-01
Time elapsed (hh:mm:ss.ms) 0:00:00.814024


export 33056 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2019-12-01 to 2019-12-01
Time elapsed (hh:mm:ss.ms) 0:00:00.671227


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2019-12-08 to 2019-12-08
Time elapsed (hh:mm:ss.ms) 0:00:00.475823


export 32202 completed!




Retrieving weather data for 32202


Currently retrieving data for 32202: from 2019-12-29 to 2019-12-29
Time elapsed (hh:mm:ss.ms) 0:00:00.483215


export 32202 completed!




Retrieving weather data for 98134


Currently retrieving data for 98134: from 2020-09-20 to 2020-09-20
Time elapsed (hh:mm:ss.ms) 0:00:00.581792


export 98134 completed!




Retrieving weather data for 60605


Currently retrieving data for 60605: from 2020-09-20 to 2020-09-20
Time elapsed (hh:mm:ss.ms) 0:00:00.615438


export 60605 completed!




Retrieving weather data for 28202


Currently retrieving data for 28202: from 2020-11-22 to 2020-11-22
Time elapsed (hh:mm:ss.ms) 0:00:00.468667


export 28202 completed!




Retrieving weather data for 64129


Currently retrieving data for 64129: from 2020-12-27 to 2020-12-27
Time elapsed (hh:mm:ss.ms) 0:00:00.464032


export 64129 completed!




Retrieving weather data for HA9


Currently retrieving data for HA9: from 2015-11-01 to 2015-11-01
Time elapsed (hh:mm:ss.ms) 0:00:00.470899


export HA9 completed!




Retrieving weather data for HA9


Currently retrieving data for HA9: from 2017-09-24 to 2017-09-24
Time elapsed (hh:mm:ss.ms) 0:00:01.534699


export HA9 completed!

In [93]:
#missed the last one somehow
zipcode = [weather["zip"][70]]#the function wants a list
temp = retrieve_hist_data("d44e502519aa4821af5205304211704",
                            zipcode,
                            weather["game_date"][70],
                            weather["game_date"][70],
                            6,
                            location_label = False,
                            export_csv = True,
                            store_df = True)
hist_weather_data.append(temp)

Retrieving weather data for HA9


Currently retrieving data for HA9: from 2017-10-01 to 2017-10-01
Time elapsed (hh:mm:ss.ms) 0:00:00.911623


export HA9 completed!

In [86]:
i

5

In [94]:
hist_weather_data[70]

[            date_time maxtempC mintempC totalSnow_cm sunHour uvIndex  \
 0 2017-10-01 00:00:00       17       15          0.0     5.7       4
 1 2017-10-01 06:00:00       17       15          0.0     5.7       4
 2 2017-10-01 12:00:00       17       15          0.0     5.7       4
 3 2017-10-01 18:00:00       17       15          0.0     5.7       4

   moon_illumination  moonrise   moonset   sunrise  ... WindGustKmph  \
 0                72  05:00 PM  01:42 AM  07:02 AM  ...           34
 1                72  05:00 PM  01:42 AM  07:02 AM  ...           22
 2                72  05:00 PM  01:42 AM  07:02 AM  ...           25
 3                72  05:00 PM  01:42 AM  07:02 AM  ...           30

   cloudcover humidity precipMM pressure tempC visibility winddirDegree  \
 0        100       83      0.7     1013    15          2           182
 1        100       89      0.5     1012    16          2           184
 2        100       77      0.0     1011    17         10           203
 3        100       88      0.6     1010    17          2           200

   windspeedKmph location
 0            23      HA9
 1            15      HA9
 2            19      HA9
 3            19      HA9

 [4 rows x 25 columns]]

In [129]:
pd_hist_weather_data = hist_weather_data[0][0]
for i in range(len(weather)-2):
    pd_hist_weather_data = pd_hist_weather_data.append(hist_weather_data[i+1][0])
pd_hist_weather_data

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2015-09-13 00:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,10,100,98,0.0,1011,23,0,251,6,32202
1,2015-09-13 06:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,14,30,93,0.1,1013,21,10,338,9,32202
2,2015-09-13 12:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,5,7,41,0.0,1014,29,10,319,4,32202
3,2015-09-13 18:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,11,0,51,0.0,1015,24,10,350,5,32202
0,2015-09-20 00:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,13,69,80,0.3,1016,25,10,99,7,32202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2015-11-01 18:00:00,19,11,0.0,8.7,5,59,10:11 PM,12:55 PM,07:54 AM,...,20,0,89,0.0,1028,14,10,106,10,HA9
0,2017-09-24 00:00:00,21,14,0.0,11.6,5,22,11:16 AM,09:10 PM,06:51 AM,...,17,47,65,0.0,1020,14,10,137,10,HA9
1,2017-09-24 06:00:00,21,14,0.0,11.6,5,22,11:16 AM,09:10 PM,06:51 AM,...,15,3,84,0.0,1020,14,10,135,11,HA9
2,2017-09-24 12:00:00,21,14,0.0,11.6,5,22,11:16 AM,09:10 PM,06:51 AM,...,17,9,51,0.0,1020,21,10,137,14,HA9
3,2017-09-24 18:00:00,21,14,0.0,11.6,5,22,11:16 AM,09:10 PM,06:51 AM,...,13,39,58,0.0,1019,19,10,134,9,HA9

In [131]:
#missed one. again..
pd_hist_weather_data = pd_hist_weather_data.append(hist_weather_data[70][0])
pd_hist_weather_data
#and... accidentally put 4 extra rows on. just gonna export to excel since
#i'm doing the more complex analysis there

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2015-09-13 00:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,10,100,98,0.0,1011,23,0,251,6,32202
1,2015-09-13 06:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,14,30,93,0.1,1013,21,10,338,9,32202
2,2015-09-13 12:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,5,7,41,0.0,1014,29,10,319,4,32202
3,2015-09-13 18:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,11,0,51,0.0,1015,24,10,350,5,32202
0,2015-09-20 00:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,13,69,80,0.3,1016,25,10,99,7,32202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,2017-10-01 18:00:00,17,15,0.0,5.7,4,72,05:00 PM,01:42 AM,07:02 AM,...,30,100,88,0.6,1010,17,2,200,19,HA9
0,2017-10-01 00:00:00,17,15,0.0,5.7,4,72,05:00 PM,01:42 AM,07:02 AM,...,34,100,83,0.7,1013,15,2,182,23,HA9
1,2017-10-01 06:00:00,17,15,0.0,5.7,4,72,05:00 PM,01:42 AM,07:02 AM,...,22,100,89,0.5,1012,16,2,184,15,HA9
2,2017-10-01 12:00:00,17,15,0.0,5.7,4,72,05:00 PM,01:42 AM,07:02 AM,...,25,100,77,0.0,1011,17,10,203,19,HA9
3,2017-10-01 18:00:00,17,15,0.0,5.7,4,72,05:00 PM,01:42 AM,07:02 AM,...,30,100,88,0.6,1010,17,2,200,19,HA9

In [126]:
#this is all troubleshooting for above^^
'''
temp = hist_weather_data[0][0]
pd_hist_weather_data = temp.append(hist_weather_data[1][0])
pd_hist_weather_data
#pd_hist_weather_data = pd_hist_weather_data.append(hist_weather_data[2][0])
#del pd_hist_weather_data
i = 0
print(4*(i+1)-3)
print(4*(i+1)-2)
print(4*(i+1)-1)
print(4*(i+1))
i = 1
print(4*(i+1)-3)
print(4*(i+1)-2)
print(4*(i+1)-1)
print(4*(i+1))

,date_time,maxtempC,mintempC,totalSnow_cm,sunHour,uvIndex,moon_illumination,moonrise,moonset,sunrise,...,WindGustKmph,cloudcover,humidity,precipMM,pressure,tempC,visibility,winddirDegree,windspeedKmph,location
0,2015-09-13 00:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,10,100,98,0.0,1011,23,0,251,6,32202
1,2015-09-13 06:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,14,30,93,0.1,1013,21,10,338,9,32202
2,2015-09-13 12:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,5,7,41,0.0,1014,29,10,319,4,32202
3,2015-09-13 18:00:00,29,21,0.0,11.6,6,0,07:25 AM,07:51 PM,07:10 AM,...,11,0,51,0.0,1015,24,10,350,5,32202
0,2015-09-20 00:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,13,69,80,0.3,1016,25,10,99,7,32202
1,2015-09-20 06:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,11,52,70,0.3,1015,27,10,81,7,32202
2,2015-09-20 12:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,6,4,41,0.0,1014,33,10,29,5,32202
3,2015-09-20 18:00:00,33,23,0.0,11.6,6,47,01:31 PM,No moonset,07:14 AM,...,15,8,67,0.0,1012,25,10,98,7,32202

In [132]:
pd_hist_weather_data.to_csv('pd_hist_weather_data.csv')